firstname = input("Enter firstname :")
print("My firstname is", firstname)
surname = input("Enter your surname :")
print("My surname is",surname)
school = input("Enter your school name :")
print("My school is",school)